// License: GNU AGPLv3 or higher
//
// Evidence generator for the fibre-tail release / preheat-ordering work.
//
// It CALLS the shipped planner and emitter (Fiber::plan_tail_release_distances,
// Fiber::select_release_seam, Fiber::rotate_closed_path, Fiber::plan_fiber_release,
// Fiber::emit_fiber_release, Fiber::plan_tool_preheat, Fiber::emit_tool_preheat,
// Fiber::evidence_manifest_to_json) and writes the artifacts those calls produce.
// Nothing here is a hand-written copy of an expected string: if the planner
// changes, the artifacts change with it.
//
// HONESTY NOTE: the editable S-hook project and the owner's baseline export are
// files outside this repository, so the three shook_* files written here are
// DETERMINISTIC STAND-IN EXPORTS built from the shipped planner over a
// representative S-hook-shaped closed path. They are NOT a re-slice of the
// baseline and say so in their own headers.

#include <cmath>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include "libslic3r/Fiber/FiberTailRelease.hpp"
#include "libslic3r/Fiber/FiberToolChange.hpp" // fiber_cycle_net_stationary_v_mm

using namespace Slic3r::Fiber;

namespace {

std::string hdr(const std::string& variant, const std::string& note,
              const std::string& meta = std::string())
{
    std::string s;
    // Analyzer metadata. The analyzer strips '#' lines before parsing, so
    // these describe the export to the checker without changing the program
    // the printer would see. Declaring the expectations here is what makes
    // the exports checkable rather than merely readable.
    s += meta;
    s += "; FibreSeeker3 tail/release comparison export\n";
    s += "; variant: " + variant + "\n";
    s += "; generated by gen_tail_release_evidence from the shipped Fiber:: planner/emitter\n";
    s += "; " + note + "\n";
    s += "; clock: nominal commanded motion; temperature waits and opaque macros contribute zero\n";
    s += "; acceleration and heater behaviour are NOT modelled\n";
    s += "; physical_tail_clearance: unmeasured\n";
    s += "; macro_contract: MACRO_CONTRACT_UNVERIFIED\n";
    s += "; print_quality: UNTESTED (static export verification only)\n";
    s += "M82\nM83\nG90\n";
    return s;
}

// A representative S-hook-shaped CLOSED path: long straight, hook, long straight
// back, closed. Deterministic, so the seam choice is reproducible.
std::vector<FiberPoint> shook_path()
{
    return {
        FiberPoint{20.0, 30.0}, FiberPoint{80.0, 30.0},  // 60 mm straight
        FiberPoint{92.0, 36.0}, FiberPoint{92.0, 48.0},  // the hook
        FiberPoint{80.0, 54.0}, FiberPoint{20.0, 54.0},  // 60 mm straight back
        FiberPoint{20.0, 30.0},                          // close
    };
}

double path_length(const std::vector<FiberPoint>& p)
{
    double t = 0.0;
    for (size_t i = 0; i + 1 < p.size(); ++i)
        t += std::hypot(p[i + 1].x - p[i].x, p[i + 1].y - p[i].y);
    return t;
}

// Walk `path` from its start, emitting joint U/V deposits until `cut_at`, then
// V-only tail deposits for `tail_len`. Appends the cut handshake at the boundary.
void walk_deposit(std::string& s,
                  const std::vector<FiberPoint>& path,
                  double cut_at,
                  double tail_len,
                  double ratio_p,
                  double fiber_rate,
                  double feed)
{
    char buf[160];
    double cum = 0.0;
    bool cut = false;
    double tail_left = tail_len;

    for (size_t i = 0; i + 1 < path.size(); ++i) {
        const double dx = path[i + 1].x - path[i].x;
        const double dy = path[i + 1].y - path[i].y;
        const double len = std::sqrt(dx * dx + dy * dy);
        if (len <= 1e-9)
            continue;

        if (!cut) {
            if (cum + len <= cut_at + 1e-9) {
                // Whole segment is body.
                const double u = len * fiber_rate;
                std::snprintf(buf, sizeof(buf), "G1 X%.3f Y%.3f U%.3f V%.3f F%.0f",
                              FiberRun::round3(path[i + 1].x), FiberRun::round3(path[i + 1].y),
                              FiberRun::round3(u), FiberRun::round3(u * ratio_p), feed);
                s += std::string(buf) + "\n";
                cum += len;
                continue;
            }
            // The cut falls inside this segment: body up to the cut point.
            const double t = (cut_at - cum) / len;
            const double bx = path[i].x + dx * t;
            const double by = path[i].y + dy * t;
            const double bu = (cut_at - cum) * fiber_rate;
            if (bu > 0.0005) {
                std::snprintf(buf, sizeof(buf), "G1 X%.3f Y%.3f U%.3f V%.3f F%.0f",
                              FiberRun::round3(bx), FiberRun::round3(by),
                              FiberRun::round3(bu), FiberRun::round3(bu * ratio_p), feed);
                s += std::string(buf) + "\n";
            }
            s += "; Start to cut\nM2800\nM400\n";
            cut = true;
            // Remaining part of this segment is tail, then following segments.
            double px = bx, py = by;
            double seg_left = len * (1.0 - t);
            size_t j = i;
            while (tail_left > 1e-6) {
                const double step = std::min(tail_left, seg_left);
                if (step <= 1e-9)
                    break;
                const double nx = px + (path[j + 1].x - px) * (step / seg_left);
                const double ny = py + (path[j + 1].y - py) * (step / seg_left);
                std::snprintf(buf, sizeof(buf), "G1 X%.3f Y%.3f V%.3f F%.0f",
                              FiberRun::round3(nx), FiberRun::round3(ny),
                              FiberRun::round3(step * fiber_rate * ratio_p), feed);
                s += std::string(buf) + "\n";
                tail_left -= step;
                px = nx;
                py = ny;
                if (step >= seg_left - 1e-9 && j + 2 < path.size()) {
                    ++j;
                    seg_left = std::hypot(path[j + 1].x - path[j].x, path[j + 1].y - path[j].y);
                    px = path[j].x;
                    py = path[j].y;
                } else {
                    break;
                }
            }
            s += "; Cutting completed.\n";
            break;
        }
    }
    if (!cut)
        s += "; FS_RELEASE_UNSUPPORTED cut position beyond path end\n";
    s += "G1 F600 V-1.000 ; Retract\n";
}

// The ordered transition block: sync, the one V-4 for the real departure, the
// lift, then the station visit with the blocking wait INSIDE it, then the switch
// and the E recovery at the next deposition start.
std::string transition_block(double z)
{
    char buf[96];
    std::string s;
    s += "M400\n";
    s += "G1 F600 V-4.000 ; Toolchange matrix retract\n";
    std::snprintf(buf, sizeof(buf), "G1 Z%.3f F1200\n", z + 0.6);
    s += std::string(buf);
    s += "MOVE_TO_BRUSH_STATION\n";
    s += "M400\n";
    s += "; FS_STATION_ENTER tool=0\n";
    s += "CLEAN_NOZZLE\n";
    s += "M104 S180 T0 ; standby\n";
    s += "M104 S250 T1 ; pre-charge\n";
    s += "; FS_WAIT_BEGIN tool=1 target_c=250 location=brush_station\n";
    s += "M109 S250 T1\n";
    s += "; FS_WAIT_END tool=1\n";
    s += "MOVE_OUT_BRUSH_STATION\n";
    s += "; FS_STATION_EXIT\n";
    s += "T1 ; switch extruder type to:PLASTIC\n";
    s += "G90\nM83\n";
    std::snprintf(buf, sizeof(buf), "G1 X20.000 Y30.000 Z%.3f F3000\n", z);
    s += std::string(buf);
    s += "G1 E10.000 U0.000 F1500 ; recovery at the next deposition start\n";
    return s;
}

bool write_file(const std::string& path, const std::string& content)
{
    std::ofstream f(path, std::ios::binary | std::ios::out);
    if (!f) {
        std::cout << "CANNOT WRITE " << path << "\n";
        return false;
    }
    f << content;
    return true;
}

class SolidBase : public ReleaseSupportModel
{
public:
    SupportVerdict query(const ReleaseSupportQuery&) const override
    {
        return SupportVerdict::Supported; // calibration fixture has a solid base
    }
};

// One straight-tail calibration fixture: solid supporting base, five repeated
// straight strands at one margin, each closing its window and releasing.
std::string straight_fixture(const TailReleaseParams& tp, const std::string& variant)
{
    char buf[200];
    char mbuf[160];
    std::snprintf(mbuf, sizeof(mbuf), "# OPT: release_mm=%.1f\n",
                  tp.release_mm);
    const std::string meta = std::string(mbuf)
        + "# EXPECT: WARN FS_MACRO_CONTRACT_UNVERIFIED\n";
    std::string s = hdr(variant, "straight-tail calibration fixture: solid base + 5 strands", meta);
    s += "; margin_mm=" + std::to_string(tp.margin_mm) + "\n";
    s += "; release_mm=" + std::to_string(tp.release_mm) + "\n";
    const SolidBase base;
    for (int w = 0; w < 5; ++w) {
        const double y = 10.0 + 6.0 * w;
        const std::vector<FiberPoint> pts{FiberPoint{0.0, y}, FiberPoint{100.0, y}};
        TailReleaseDistances d;
        std::string err;
        if (!plan_tail_release_distances(100.0, tp, d, &err)) {
            s += "; FS_RELEASE_UNSUPPORTED " + err + "\n";
            continue;
        }
        ReleasePlan rel;
        if (!plan_fiber_release(pts, false, 0.2, tp, &base, rel, &err)) {
            s += "; FS_RELEASE_UNSUPPORTED " + err + "\n";
            continue;
        }
        s += "M1001 L120\n";
        std::snprintf(buf, sizeof(buf), "; STRAND %d cut_x=%.3f post_cut_deposit=%.3f\n",
                      w, d.cut_distance_mm, d.post_cut_deposit_mm);
        s += std::string(buf);
        walk_deposit(s, pts, d.cut_distance_mm, d.post_cut_deposit_mm, 2.0, 0.5, 3000.0);
        s += emit_fiber_release(rel);
        s += "M1002\n";
        s += transition_block(0.2);
    }
    return s;
}

} // namespace

int main(int argc, char** argv)
{
    const std::string dir = argc > 1 ? argv[1] : ".";
    const double ratio_p = 2.0;
    const double fiber_rate = 0.5;
    const double feed = 3000.0;

    TailReleaseParams a;                       // R 0, M 0
    TailReleaseParams b;  b.release_mm = 6.8;  // R 6.8, M 0
    TailReleaseParams c;  c.release_mm = 6.8; c.margin_mm = 1.0;

    std::vector<TailReleaseEvidence> records;
    const char* names[3] = {"shook_A_park_wait", "shook_B_forward_release", "shook_C_release_margin_1mm"};
    TailReleaseParams params[3] = {a, b, c};

    std::string seam_b, seam_c;
    for (int vi = 0; vi < 3; ++vi) {
        const TailReleaseParams& tp = params[vi];
        const std::string name = names[vi];
        const auto path0 = shook_path();
        TailReleaseDistances d;
        std::string err;
        if (!plan_tail_release_distances(path_length(path0), tp, d, &err)) {
            std::cout << "DIST FAIL " << name << ": " << err << "\n";
            return 1;
        }
        std::vector<FiberPoint> path = path0;
        ReleaseSeam seam;
        if (tp.release_mm > 0.0) {
            if (!select_release_seam(path0, true, tp, seam, &err)) {
                std::cout << "SEAM FAIL " << name << ": " << err << "\n";
                return 1;
            }
            path = rotate_closed_path(path0, seam.seam_distance_mm);
        }
        ReleasePlan rel;
        if (!plan_fiber_release(path, tp.release_mm > 0.0, 0.2, tp, nullptr, rel, &err)) {
            std::cout << "RELEASE FAIL " << name << ": " << err << "\n";
            return 1;
        }

        // Preheat over a modelled outgoing activation: the deposition, then an
        // opaque macro, then the blocking wait (which costs zero by contract).
        std::vector<MotionBlock> act;
        MotionBlock dep;
        dep.kind = MotionBlock::Kind::Deposit;
        dep.path_mm = d.planned_length_mm;
        dep.feed_mm_min = feed;
        act.push_back(dep);
        MotionBlock mac;
        mac.kind = MotionBlock::Kind::Macro;
        act.push_back(mac);
        MotionBlock wait;
        wait.kind = MotionBlock::Kind::TempWait;
        act.push_back(wait);
        const PreheatPlan pre = plan_tool_preheat(act, 1, 250, 15.0);

        char buf[200];
        char mbuf[160];
        std::snprintf(mbuf, sizeof(mbuf), "# OPT: release_mm=%.1f\n",
                      tp.release_mm);
        const std::string meta = std::string(mbuf)
            + "# EXPECT: WARN FS_MACRO_CONTRACT_UNVERIFIED\n"
            // The S-hook stand-in really does turn sharply after the cut, so the
            // sharp-turn warning is expected here rather than suppressed.
            + "# EXPECT: WARN FS_TAIL_SHARP_TURN\n";
        std::string out = hdr(name, "DETERMINISTIC STAND-IN EXPORT - not a re-slice of the owner baseline", meta);
        std::snprintf(buf, sizeof(buf),
                      "; planned_length_mm=%.3f cut_distance_mm=%.3f post_cut_deposit_mm=%.3f "
                      "post_cut_xy_total_mm=%.3f\n",
                      d.planned_length_mm, d.cut_distance_mm, d.post_cut_deposit_mm, d.post_cut_xy_mm);
        out += std::string(buf);
        std::snprintf(buf, sizeof(buf), "; seam_distance_mm=%.3f rotation_mm=%.3f\n",
                      seam.seam_distance_mm, seam.rotation_mm);
        out += std::string(buf);
        std::snprintf(buf, sizeof(buf), "; preheat_insert_index=%zu nominal_lead_s=%.3f clamped=%d\n",
                      pre.insert_index, pre.nominal_lead_s, pre.clamped_to_activation ? 1 : 0);
        out += std::string(buf);
        out += "M1001 L120\n";
        out += emit_tool_preheat(pre);
        walk_deposit(out, path, d.cut_distance_mm, d.post_cut_deposit_mm, ratio_p, fiber_rate, feed);
        out += emit_fiber_release(rel);
        out += "M1002\n";
        out += transition_block(0.2);

        const std::string fname = dir + "/" + name + ".gcode";
        if (!write_file(fname, out))
            return 1;
        std::cout << "WROTE " << fname << "\n";

        if (tp.release_mm > 0.0) {
            TailReleaseEvidence e;
            e.object_id = "shook-standin";
            e.layer_index = 1;
            e.physical_z = 0.2;
            e.window_id = name;
            e.original_seam = "none";
            e.selected_seam = "run@" + std::to_string(seam.seam_distance_mm);
            e.rotation_mm = seam.rotation_mm;
            e.nominal_tail_mm = tp.nominal_tail_mm;
            e.margin_mm = tp.margin_mm;
            e.requested_release_mm = tp.release_mm;
            e.actual_release_mm = rel.planned_mm;
            e.post_cut_deposit_mm = d.post_cut_deposit_mm;
            e.cut_xyz = FiberPoint{d.cut_distance_mm, 30.0};
            e.deposit_end_xyz = path.back();
            e.release_end_xyz = rel.end;
            e.release_speed_mm_s = tp.release_speed_mm_s;
            e.anchor_mm = tp.anchor_mm;
            e.bead_width_mm = tp.bead_width_mm;
            e.support_result = rel.closed ? "SUPPORTED_BY_OWN_DEPOSITION" : "NOT_EVALUATED";
            e.stationary_v_mm = fiber_cycle_net_stationary_v_mm(4.0, 1.0, 4.0);
            e.budget_L = 120;
            records.push_back(e);
            if (name.find("shook_B") != std::string::npos)
                seam_b = e.selected_seam;
            if (name.find("shook_C") != std::string::npos)
                seam_c = e.selected_seam;
        }
    }

    // Straight-tail calibration fixtures at the five spec'd margins.
    const double margins[5] = {0.0, 0.5, 1.0, 1.5, 2.0};
    const char* tag[5] = {"0p0", "0p5", "1p0", "1p5", "2p0"};
    for (int i = 0; i < 5; ++i) {
        TailReleaseParams tp;
        tp.margin_mm = margins[i];
        tp.release_mm = 6.8;
        const std::string fname = dir + "/straight_tail_margin_" + tag[i] + ".gcode";
        if (!write_file(fname, straight_fixture(tp, "straight_tail_margin_" + std::string(tag[i]))))
            return 1;
        std::cout << "WROTE " << fname << "\n";
    }

    if (!write_file(dir + "/tail_release_evidence.json", evidence_manifest_to_json(records, "shook_standin_set")))
        return 1;
    std::cout << "WROTE " << dir + "/tail_release_evidence.json\n";
    std::cout << "SEAM_B=" << seam_b << "\nSEAM_C=" << seam_c << "\n";
    std::cout << (seam_b == seam_c ? "SEAM_MATCH: PASS (margin did not change the seam)\n"
                                   : "SEAM_MATCH: FAIL\n");
    return 0;
}
